version: '2'
services:
  zk:
    image: avvo/zookeeper
    # build: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: avvo/kafka
    # build: kafka
    ports:
      - 9092:9092
    links:
      - zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 12
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
